import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def run(cmd: list[str], cwd: Path, timeout: int = 600, allow_fail: bool = False) -> int:
    print("$ " + " ".join(cmd), flush=True)
    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    completed = subprocess.run(
        cmd,
        cwd=str(cwd),
        env=env,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    if completed.stdout:
        print(completed.stdout, end="", flush=True)
    if completed.stderr:
        print(completed.stderr, end="", file=sys.stderr, flush=True)
    if completed.returncode != 0 and not allow_fail:
        raise subprocess.CalledProcessError(completed.returncode, cmd, completed.stdout, completed.stderr)
    return int(completed.returncode)


def config_to_extract_args(config_path: Path, out_dir_abs: Path) -> list[str]:
    """Export qcvv_config.json into dt/state-label files and return extract args."""
    py = sys.executable or "python"
    rc = run([py, "-m", "src.qcvv.qcvv_config", "--config", str(config_path), "--export", str(out_dir_abs)], cwd=config_path.parent, timeout=120, allow_fail=True)
    # Validation warnings are okay, errors return 2. Still use any exported partial files if present.
    dt_path = out_dir_abs / "dt.json"
    labels_path = out_dir_abs / "state_labels.json"
    args: list[str] = []
    if dt_path.exists():
        try:
            dt_data = json.loads(dt_path.read_text(encoding="utf-8"))
        except Exception:
            dt_data = {}
        if dt_data:
            args += ["--dt-json", str(dt_path)]
    if labels_path.exists():
        try:
            labels_data = json.loads(labels_path.read_text(encoding="utf-8"))
        except Exception:
            labels_data = {}
        if labels_data:
            args += ["--state-label-json", str(labels_path)]
    if rc != 0:
        print("QCVV config validation reported errors; extraction will continue with any usable exported values.", file=sys.stderr)
    return args


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run official-readiness QCVV extraction, uncertainty, drift, figures, and reports.")
    parser.add_argument("--project-root", default=".", help="Project root containing pipeline/ and individual/ folders.")
    parser.add_argument("--out-dir", default="qcvv_outputs", help="Output directory, relative to project root unless absolute.")
    parser.add_argument("--bundles", choices=["both", "pipeline", "individual"], default="both", help="Which bundle(s) to scan. Default: both.")
    parser.add_argument("--dt-json", default=None, help="Optional family -> physical timestep JSON file.")
    parser.add_argument("--state-label-json", default=None, help="Optional physical state-label map JSON file.")
    parser.add_argument("--qcvv-config", default=None, help="Optional full physical QCVV config JSON generated by qcvv_config.py.")
    parser.add_argument("--include-individual", action="store_true", help="Legacy flag; both bundles are included by default.")
    parser.add_argument("--skip-figures", action="store_true", help="Skip plot generation.")
    parser.add_argument("--skip-uncertainty", action="store_true", help="Skip bootstrap uncertainty outputs.")
    parser.add_argument("--skip-drift", action="store_true", help="Skip drift outputs.")
    parser.add_argument("--n-bootstrap", type=int, default=200, help="Bootstrap replicates for uncertainty outputs.")
    parser.add_argument("--n-drift-bins", type=int, default=20, help="Number of bins for drift diagnostics.")
    args = parser.parse_args(argv)

    project_root = Path(args.project_root).resolve()
    out_dir = Path(args.out_dir)
    out_dir_abs = out_dir if out_dir.is_absolute() else project_root / out_dir
    out_dir_abs.mkdir(parents=True, exist_ok=True)

    py = sys.executable or "python"
    extract_cmd = [
        py,
        "-m",
        "src.qcvv.qcvv_extract",
        "--project-root",
        str(project_root),
        "--out-dir",
        str(out_dir_abs),
        "--bundles",
        args.bundles,
    ]
    if args.qcvv_config:
        extract_cmd += config_to_extract_args(Path(args.qcvv_config).resolve(), out_dir_abs)
    if args.dt_json:
        extract_cmd += ["--dt-json", args.dt_json]
    if args.state_label_json:
        extract_cmd += ["--state-label-json", args.state_label_json]

    run(extract_cmd, cwd=project_root, timeout=600)

    if not args.skip_uncertainty:
        unc_cmd = [
            py,
            "-m",
            "src.qcvv.qcvv_uncertainty",
            "--project-root",
            str(project_root),
            "--out-dir",
            str(out_dir_abs),
            "--n-bootstrap",
            str(args.n_bootstrap),
        ]
        if args.skip_figures:
            unc_cmd.append("--skip-figures")
        run(unc_cmd, cwd=project_root, timeout=900, allow_fail=True)

    if not args.skip_drift:
        drift_cmd = [
            py,
            "-m",
            "src.qcvv.qcvv_drift",
            "--project-root",
            str(project_root),
            "--out-dir",
            str(out_dir_abs),
            "--n-bins",
            str(args.n_drift_bins),
        ]
        if args.skip_figures:
            drift_cmd.append("--skip-figures")
        run(drift_cmd, cwd=project_root, timeout=600, allow_fail=True)

    if not args.skip_figures:
        run([py, "-m", "src.qcvv.qcvv_visualize", "--out-dir", str(out_dir_abs)], cwd=project_root, timeout=420, allow_fail=True)

    run([py, "-m", "src.qcvv.qcvv_report", "--out-dir", str(out_dir_abs)], cwd=project_root, timeout=300)
    run([py, "-m", "src.qcvv.qcvv_official_interpretation", "--out-dir", str(out_dir_abs)], cwd=project_root, timeout=300)

    print(f"Official-readiness QCVV workflow complete: {out_dir_abs}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
